# Generated by Django 3.0 on 2022-06-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretary', '0001_initial'),
        ('applies', '0001_initial'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='secretary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='secretary.Secretary'),
        ),
        migrations.AddField(
            model_name='apply',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
